name: Build static site
on: [push]
jobs:
  Build-static-site:
    runs-on: ubuntu-latest
    steps:
      - name: Setup php 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: composer install
      - run: mkdir -p public/tag
      - run: php build.php
      - run: git checkout static-pages
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/ 
          git commit -m "automatic deploy"
          git push
